// Exercise Categories
const EXERCISE_CATEGORIES = {
Chest: [
  "Bench Press",
  "Incline Bench Press",
  "Decline Bench Press",
  "Flat Dumbbell Press",
  "Incline Dumbbell Press",
  "Decline Dumbbell Press",
  "Chest Fly (Machine)",
  "Dumbbell Fly",
  "Cable Fly",
  "Low-to-High Cable Fly",
  "High-to-Low Cable Fly",
  "Push-Up",
  "Weighted Push-Up",
  "Chest Dip",
  "Smith Machine Bench Press",
  "Machine Chest Press",
  "Svend Press",
  "Close-Grip Bench Press",
  "Wide-Grip Bench Press",
  "Reverse-Grip Bench Press",
  "Guillotine Press",
  "Spoto Press",
  "Floor Press",
  "Decline Dumbbell Fly",
  "Incline Dumbbell Fly",
  "Dumbbell Pullover",
  "Crush Grip Dumbbell Press",
  "Alternating Dumbbell Press",
  "Single-Arm Dumbbell Bench Press",
  "Single-Arm Cable Fly",
  "Standing Cable Press",
  "Cable Crossover",
  "Hammer Strength Chest Press",
  "Hammer Strength Incline Press",
  "Hammer Strength Decline Press",
  "Pec Deck Machine",
  "Iso-Lateral Chest Press",
  "Archer Push-Up",
  "Decline Push-Up",
  "Incline Push-Up",
  "Explosive Push-Up",
  "Clap Push-Up",
  "Ring Push-Up",
  "Ring Chest Fly",
  "Landmine Chest Press",
  "Landmine Fly",
  "Banded Push-Up",
  "Banded Bench Press",
  "Banded Chest Fly",
  "Medicine Ball Chest Throw",
  "Isometric Chest Squeeze",
  "Plate Pinch Press"
],

Back: [
  "Deadlift",
  "Romanian Deadlift",
  "Lat Pulldown",
  "Wide-Grip Pulldown",
  "Close-Grip Pulldown",
  "Barbell Row",
  "Pendlay Row",
  "Dumbbell Row",
  "Chest-Supported Row",
  "Seated Cable Row",
  "T-Bar Row",
  "Machine Row",
  "Pull-Up",
  "Chin-Up",
  "Neutral-Grip Pull-Up",
  "Straight-Arm Pulldown",
  "Back Extension",
  "Good Morning",
  "Single-Arm Lat Pulldown",
  "Kneeling Single-Arm Cable Pulldown",
  "Meadows Row",
  "Lat-Focused Machine Pulldown",
  "Behind-the-Neck Pulldown",
  "Assisted Pull-Up",
  "Straight-Bar Cable Pulldown",
  "Dumbbell Pullover",
  "Yates Row",
  "Seal Row",
  "Kroc Row",
  "Wide-Grip Barbell Row",
  "Wide-Grip Seated Row",
  "Machine High Row",
  "Hammer Strength Iso-Row",
  "Reverse-Grip Barbell Row",
  "Reverse-Grip Seated Row",
  "Cable Face Pull",
  "Rear Delt Row",
  "Barbell Hip Extension",
  "45-Degree Hyperextension",
  "Reverse Hyperextension",
  "Rack Pull",
  "Jefferson Curl",
  "Cable Low Back Extension",
  "Rope Straight-Arm Pulldown",
  "Single-Arm Seated Cable Row",
  "High-to-Low Cable Row",
  "Low-to-High Cable Row",
  "Cable Rear Delt Fly",
  "Hammer Strength Low Row",
  "Hammer Strength High Row",
  "Nautilus Pullover Machine",
  "Plate-Loaded Iso-Lateral Row",
  "Selectorized Lat Row Machine",
  "Inverted Row",
  "TRX Row",
  "TRX Face Pull",
  "Superman Hold",
  "Archer Pull-Up",
  "Typewriter Pull-Up"
],

Shoulders: [
  "Overhead Press",
  "Seated Dumbbell Shoulder Press",
  "Arnold Press",
  "Machine Shoulder Press",
  "Lateral Raise",
  "Cable Lateral Raise",
  "Dumbbell Front Raise",
  "Barbell Front Raise",
  "Rear Delt Fly",
  "Reverse Pec Deck",
  "Face Pull",
  "Upright Row",
  "Landmine Press",
  "Single-Arm Cable Press",
  "Standing Dumbbell Shoulder Press",
  "Z Press",
  "Push Press",
  "Behind-the-Neck Press",
  "Machine Lateral Raise",
  "Leaning Dumbbell Lateral Raise",
  "Seated Lateral Raise",
  "Single-Arm Dumbbell Lateral Raise",
  "Cable Y-Raise",
  "Dumbbell Y-Raise",
  "Plate Front Raise",
  "Rope Front Raise",
  "Cable Rear Delt Row",
  "Bent-Over Dumbbell Reverse Fly",
  "Incline Bench Rear Delt Fly",
  "Prone Y-Raise",
  "Prone T-Raise",
  "Prone W-Raise",
  "Kettlebell Press",
  "Kettlebell Bottom-Up Press",
  "Kettlebell Halo",
  "Landmine Lateral Raise",
  "Landmine Meadows Press",
  "Machine Rear Delt Fly",
  "Smith Machine Shoulder Press",
  "Smith Machine Upright Row",
  "Barbell High Pull",
  "Cable High Pull",
  "TRX Y-Fly",
  "TRX T-Fly",
  "Handstand Push-Up",
  "Pike Push-Up",
  "Wall Walk"
],

Biceps: [
  "Barbell Curl",
  "Dumbbell Curl",
  "Hammer Curl",
  "Incline Dumbbell Curl",
  "Preacher Curl",
  "Cable Curl",
  "EZ-Bar Curl",
  "Concentration Curl",
  "Spider Curl",
  "Machine Bicep Curl",
  "Reverse Curl",
  "Zottman Curl",
  "Alternating Dumbbell Curl",
  "Seated Dumbbell Curl",
  "Standing Cable Curl",
  "Rope Cable Curl",
  "Bayesian Cable Curl",
  "Single-Arm Cable Curl",
  "Single-Arm Preacher Curl",
  "Cross-Body Hammer Curl",
  "Pinwheel Curl",
  "Kettlebell Curl",
  "Kettlebell Hammer Curl",
  "Barbell Drag Curl",
  "Dumbbell Drag Curl",
  "High Cable Curl",
  "Low Cable Curl",
  "Behind-the-Back Cable Curl",
  "Incline Hammer Curl",
  "Prone Incline Curl",
  "Reverse-Grip EZ-Bar Curl",
  "Wide-Grip Barbell Curl",
  "Close-Grip Barbell Curl",
  "21s (Bicep Curl)",
  "Isometric Bicep Hold",
  "Resistance Band Curl",
  "Resistance Band Hammer Curl",
  "TRX Bicep Curl"
],

Triceps: [
  "Tricep Pushdown",
  "Rope Pushdown",
  "Straight-Bar Pushdown",
  "Skullcrusher",
  "Close-Grip Bench Press",
  "Overhead Dumbbell Extension",
  "Cable Overhead Extension",
  "Dips",
  "Bench Dip",
  "Kickback",
  "Machine Tricep Extension",
  "EZ-Bar Skullcrusher",
  "Incline Skullcrusher",
  "Seated Overhead EZ-Bar Extension",
  "Single-Arm Overhead Dumbbell Extension",
  "Single-Arm Cable Overhead Extension",
  "Cross-Body Cable Extension",
  "Reverse-Grip Pushdown",
  "V-Bar Pushdown",
  "Dual-Rope Overhead Extension",
  "Lying Cable Extension",
  "Cable Skullcrusher",
  "Barbell JM Press",
  "Smith Machine Close-Grip Press",
  "Machine Dip",
  "Ring Dip",
  "Diamond Push-Up",
  "Bodyweight Tricep Extension (TRX or Bar)",
  "Kettlebell Tricep Extension",
  "Kettlebell Skullcrusher",
  "Resistance Band Tricep Extension",
  "Resistance Band Overhead Extension"
],

Legs: [
  "Squat",
  "Front Squat",
  "Hack Squat",
  "Leg Press",
  "Lunges",
  "Walking Lunges",
  "Bulgarian Split Squat",
  "Leg Extension",
  "Hamstring Curl",
  "Romanian Deadlift",
  "Stiff-Leg Deadlift",
  "Hip Thrust",
  "Glute Bridge",
  "Calf Raise",
  "Seated Calf Raise",
  "Goblet Squat",
  "Step-Up",
  "Sumo Squat",
  "Back Squat",
  "Low-Bar Squat",
  "Box Squat",
  "Zercher Squat",
  "Anderson Squat",
  "Overhead Squat",
  "Split Squat",
  "Reverse Lunge",
  "Curtsy Lunge",
  "Deficit Lunge",
  "Pistol Squat",
  "Shrimp Squat",
  "Sissy Squat",
  "Smith Machine Squat",
  "Smith Machine Lunge",
  "Smith Machine Split Squat",
  "Machine Hack Squat",
  "Pendulum Squat",
  "V-Squat Machine",
  "Leg Press (Single-Leg)",
  "Leg Press (Wide Stance)",
  "Leg Press (Narrow Stance)",
  "Nordic Hamstring Curl",
  "Glute-Ham Raise",
  "Cable Kickback",
  "Cable Pull-Through",
  "Good Morning (Barbell)",
  "Good Morning (Safety Bar)",
  "Kettlebell Deadlift",
  "Trap Bar Deadlift",
  "Hip Abduction Machine",
  "Hip Adduction Machine",
  "Cable Hip Abduction",
  "Cable Hip Adduction",
  "Frog Pump",
  "Banded Glute Bridge",
  "Banded Squat",
  "Donkey Calf Raise",
  "Standing Calf Raise",
  "Leg Curl (Seated)",
  "Leg Curl (Lying)",
  "Leg Curl (Standing Single-Leg)",
  "Reverse Hyperextension",
  "Back Extension (45-Degree)",
  "Step-Down",
  "Lateral Step-Up",
  "Cossack Squat",
  "Jefferson Squat",
  "Jefferson Deadlift",
  "Landmine Squat",
  "Landmine Reverse Lunge",
  "Landmine Lateral Lunge"
],

Core: [
  "Plank",
  "Side Plank",
  "Cable Crunch",
  "Hanging Leg Raise",
  "Knee Raise",
  "Crunch",
  "Bicycle Crunch",
  "Russian Twist",
  "Ab Wheel Rollout",
  "Mountain Climbers",
  "Toe Touches",
  "V-Ups",
  "Dead Bug",
  "Pallof Press",
  "Weighted Sit-Up",
  "Reverse Crunch",
  "Hollow Body Hold",
  "Hollow Body Rock",
  "Flutter Kicks",
  "Scissor Kicks",
  "Jackknife Sit-Up",
  "Leg Raise",
  "Lying Leg Raise",
  "Hanging Knee Twist",
  "Oblique Crunch",
  "Side Bend (Dumbbell)",
  "Side Bend (Cable)",
  "Woodchopper (High to Low)",
  "Woodchopper (Low to High)",
  "Cable Rotation",
  "Landmine Rotation",
  "Landmine Anti-Rotation Hold",
  "Stir-the-Pot (Swiss Ball)",
  "Swiss Ball Crunch",
  "Swiss Ball Pike",
  "Swiss Ball Rollout",
  "Bird Dog",
  "Superman",
  "Back Extension (Floor)",
  "Back Extension (Machine)",
  "Hip Lift",
  "Toe-to-Bar",
  "Hanging Windshield Wipers",
  "L-Sit",
  "L-Sit Hold",
  "TRX Pike",
  "TRX Body Saw",
  "TRX Mountain Climbers",
  "Farmer Carry",
  "Suitcase Carry",
  "Overhead Carry",
  "Renegade Row",
  "Bear Crawl",
  "Bear Plank",
  "Bear Plank Shoulder Tap",
  "Copenhagen Plank"
]};

const EXERCISES = EXERCISE_CATEGORIES;

const TIMED_EXERCISES = [
  "Plank",
  "Side Plank",
  "Wall Sit",
  "Dead Hang",
  "L-Sit",
  "L-Sit Hold",
  "Farmer Carry",
  "Suitcase Carry",
  "Overhead Carry",
  "Copenhagen Plank",
  "Hollow Body Hold",
  "Hollow Body Rock",
  "Bear Plank",
  "Bear Plank Shoulder Tap",
  "Superman Hold",
  "TRX Body Saw",
  "TRX Mountain Climbers",
  "TRX Pike",
  "Landmine Anti-Rotation Hold",
  "Pallof Press",
  "Bird Dog",
  "Dead Bug",
  "Stir-the-Pot (Swiss Ball)"
];

    // Helper
function getExerciseType(name) {
  return TIMED_EXERCISES.includes(name) ? "time-weight" : "strength";
}


